blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    # Item Zone
    # http://127.0.0.1:8000/blog/
    path('', views.index, name="index" ),
    # http://127.0.0.1:8000/blog/item/1
    path('item/<int:id>', views.item_detail, name="item_detail" ),
    # http://127.0.0.1:8000/blog/register/
    path('register/', views.item_register, name="item_register" ),
    # http://127.0.0.1:8000/blog/item/modify/1/
    path("item/modify/<int:pk>/", views.item_modify, name = "item_modify"),
    # http://127.0.0.1:8000/blog/item/delete/1/
    path("item/delete/<int:pk>/", views.item_delete, name = "item_delete"),







    # Question Zone
    # http://127.0.0.1:8000/blog/qna/
    path('qna/', views.qna, name="qna" ),
    # http://127.0.0.1:8000/blog/faq
    path('faq/', views.faq, name="faq" ),
    # http://127.0.0.1:8000/blog/qna/detail/1
    path('qna/detail/<int:qid>', views.question_detail, name="question_detail" ),
    # http://127.0.0.1:8000/blog/qna/register
    path('qna/register/', views.question_register, name="question_register" ),
    # http://127.0.0.1:8000/blog/qna/modify
    path('qna/modify/<int:qid>', views.question_modify, name="question_modify" ),
    # http://127.0.0.1:8000/blog/qna/delete
    path('qna/delete/<int:qid>', views.question_delete, name="question_delete" ),




    # Answer Zone
    # http://127.0.0.1:8000/blog/answer/create/1/
    path("answer/create/<int:qid>/", views.answer_create, name="answer_create"),
    # http://127.0.0.1:8000/blog/answer/delete/1/
    path("answer/delete/<int:aid>/", views.answer_delete, name="answer_delete"),
    # http://127.0.0.1:8000/blog/answer/modify/1/
    path("answer/modify/<int:aid>/", views.answer_modify, name="answer_modify"),



    # Comment Zone
    # http://127.0.0.1:8000/blog/comment/create/answer/aid/
    path("comment/create/answer/<int:aid>/", views.comment_create_answer, name="comment_create_answer"),
    # http://127.0.0.1:8000/blog/comment/modify/answer/aid/
    path("comment/modify/answer/<int:cid>/", views.comment_modify_answer, name="comment_modify_answer"),
    # http://127.0.0.1:8000/blog/comment/delete/answer/aid/
    path("comment/delete/answer/<int:cid>/", views.comment_delete_answer, name="comment_delete_answer"),





    # Cart Zone
    #  [\w.@+-]+ : \w == 0-9A-Za-z_ ,   . == 모든문자랑 매치 ,  @+- ,  + : 1~무한대
    #  ^ : 시작, $ : 종료
    # http://127.0.0.1:8000/blog/유저이름/cart/
    re_path(r"^(?P<nickname>[\w.@+-]+)/cart/", views.cart, name="cart"), # re_path 하기

    # http://127.0.0.1:8000/blog/cart/add/item_id
    path("cart/add/<int:item_id>/", views.add_to_cart, name="add_to_cart"),  # 장바구니에 추가 기능하기

    # http://127.0.0.1:8000/blog/cart/modify/item_id
    # path("cart/modify/<int:item_id>/", views.update_quantity, name="update_quantity"),  # 장바구니에 수량 변경

   




]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index ),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from accounts.models import User
from django.db.models import UniqueConstraint

class Item(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)    
    image = models.ImageField(upload_to="image/item/")  # /media/image/
    content = models.TextField()
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]  # 기본 정렬 방식(작성일시 내림차순)

    def __str__(self) -> str:
        return self.title
    


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    # item = models.ManyToManyField(Item, through='CartItem') 
    
    def __str__(self):
        return f"{self.user.name}"



class CartItem(models.Model): # cart와 item의 중개 모델
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    added_at = models.DateTimeField(auto_now_add = True, null=True)
    updated_at = models.DateTimeField(auto_now=True)

    # class Meta:
    #     unique_together = ('cart', 'item')
    







# Question 모델
# id, subject(제목), content(내용), created_at(질문 작성일시), modified_at(질문 수정일시-직접입력(값이 없을 수도 있음))
class Question(models.Model):
    subject = models.CharField(max_length=200, verbose_name="제목")
    image = models.ImageField(upload_to="image/question_image", blank=True, verbose_name="이미지")  # /media/image/question_image
    content = models.TextField(verbose_name="내용")
    # 한사람의 user는 여러 질문을 작성할 수 있음(1:N)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_question"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성일시")
    modified_at = models.DateTimeField(blank=True, null=True, verbose_name="수정일시")
    # 하나의 질문에 여러 사람이 추천을 할 수 있다.
    # 한 사람은 여러 질문을 추천할 수 있다
    # voter = models.ManyToManyField(User, related_name="voter_question")

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return self.subject
    

# Answer 모델
# id, question(외래 키 설정), content(내용), created_at(질문 작성일시), modified_at(질문 수정일시-직접입력(값이 없을 수도 있음))
# 하나의 질문에는 여러개의 답변을 작성할 수 있다(1:N)
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="author_answer"
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성일시")
    modified_at = models.DateTimeField(blank=True, null=True, verbose_name="수정일시")

    def __str__(self) -> str:
        return self.content



# Comment (댓글) 모델
# 질문 댓글 Question_Comment - id, question, content, author, created_at, modified_at
# 답변 댓글 Answer_Comment - id, answer, content, author, created_at, modified_at
class Comment(models.Model):
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, blank=True, null=True
    )
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, blank=True, null=True)
    content = models.TextField(verbose_name="내용")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="작성일시")
    modified_at = models.DateTimeField(blank=True, null=True, verbose_name="수정일시")

    def __str__(self) -> str:
        return self.content

blog/forms.py
from django import forms
from .models import Item, Question, Answer, Comment


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ["title", "content", "image", "price"]

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["subject", "content", "image"]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["content"]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from .models import Item, Question, Answer, Comment, Cart
from .forms import ItemForm, QuestionForm, AnswerForm, CommentForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.core.paginator import Paginator
from accounts.models import User
from blog.models import Item, Cart, CartItem

from django.http import JsonResponse
from django.views.decorators.http import require_POST


# Cart 추가한 것만 보여주기
def cart(request, nickname):
    user = get_object_or_404(User, nickname=nickname ) # cart의 소유주 = user
    # item = get_object_or_404(Item, id=user.) # ??????
    

    context = {"user": user}
    return render(request, "blog/cart_page.html", context)




def add_to_cart(request, item_id): # item id가 다르게 들어와야 함
    item = get_object_or_404(Item, id=item_id)
    user = request.user

    # 수량 가져오기
    quantity = int(request.POST.get("quantity"))
    # 사용자의 cart 가져오기
    cart = get_object_or_404(Cart,user=user)

    # 사용자의 장바구니에 해당 아이템이 이미 있는지 확인
    # 만약 이미 장바구니에 있는 아이템이면 수량을 증가시킴


    try:
        cart_item = CartItem.objects.get(cart=cart, item=item)
        cart_item.quantity += quantity
        cart_item.save()

    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            item = item,
            quantity = quantity,
            cart = cart
        )
        cart_item.save()

    messages.success(request, f"{item.title}이(가) 장바구니에 추가되었습니다.")

    # cart_item, created = CartItem.objects.get_or_create(cart=cart,item=item,quantity=quantity)
    
    # if not created:
    #     cart_item.quantity += quantity
    #     cart_item.save()

    # # 여기에서는 간단하게 메시지를 추가하여 장바구니에 성공적으로 추가되었음을 알려줄 수 있습니다.
    # messages.success(request, f"{item.title}이(가) 장바구니에 추가되었습니다.")

    return redirect('blog:cart', user.nickname)  # 장바구니 페이지로 리다이렉트

































def index(request):
    items= Item.objects.all()
    page = request.GET.get("page",1)
    paginator = Paginator(items, 3)
    page_obj = paginator.get_page(page)
    context = {
        "items" : page_obj
    }

    return render(request, 'blog/index.html', context)

# item
@login_required
def item_register(request):
    """
    item 추가
    """
    if request.method == "POST":
        # request.FILES : type=file 에 들어있는 값 가져오기
        form = ItemForm(request.POST, request.FILES)
        if form.is_valid():
            # form 에 author 가 없기 때문에
            item = form.save(commit=False)
            # request.user : 현재 로그인 사용자
            item.author = request.user
            item.save()
            # # 태그 저장
            # form.save_m2m()

            return redirect("blog:index")
    else:
        form = ItemForm()

    return render(request, "blog/item_register.html", {"form": form})


def item_detail(request, id):
    item = get_object_or_404(Item, id=id)
    context={
        "item":item
    }
    return render(
        request, "blog/item_detail.html", context
    )


@login_required
def item_modify(request,pk):
    """
    질문 수정 - form 사용
    """
    item = get_object_or_404(Item, id=pk ) # 수정할 대상 찾기
    if request.method == "POST":
        form = ItemForm(request.POST, request.FILES, instance=item) # instance= 찾은 대상 적어주기. 안쓰면 create 되어버림
        if form.is_valid():
            item = form.save(commit=False)
            item.modified_at = timezone.now()
            item.save()
            return redirect("blog:item_detail", item.id)
    else:
        form = ItemForm(instance=item)
    return render(request, "blog/item_modify.html", {"form":form})


@login_required
def item_delete(request, pk):
    item = get_object_or_404(Item, id=pk)
    item.delete()
    return redirect("blog:index")


def faq(request):
    return render(request, "blog/faq.html")

def qna(request):
    """
    question 전체 목록 추출
    """
    # http://127.0.0.1:8000/board/?page=3
    # page = request.GET.get("page", 1)

    # 기본 정렬을 이용해서 목록 추출
    question_list = Question.objects.all()
    # paginator = Paginator(question_list, 10)
    # page_obj = paginator.get_page(page)

    context = {"question_list": question_list}
    
    return render(request, "blog/question_list.html", context)




# Question
@login_required
def question_register(request):
    """
    질문등록 - form 사용
    """
    if request.method == "POST":
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.save()
            return redirect("blog:question_detail", question.id)
    else:
        form = QuestionForm()
    return render(request, "blog/question_register.html", {"form": form})


def question_detail(request, qid):
    """
    Question 상세 조회
    """
    question = get_object_or_404(Question, id=qid)
    return render(request, "blog/question_detail.html", {"question": question})

@login_required
def question_modify(request,qid):
    """
    질문 수정 - form 사용
    """
    question = get_object_or_404(Question, id=qid ) # 수정할 대상 찾기
    if request.method == "POST":
        form = QuestionForm(request.POST, request.FILES, instance=question) # instance= 찾은 대상 적어주기. 안쓰면 create 되어버림
        if form.is_valid():
            question = form.save(commit=False)
            question.modified_at = timezone.now()
            question.save()
            return redirect("blog:question_detail", question.id)
    else:
        form = QuestionForm(instance=question)
    return render(request, "blog/question_modify.html", {"form":form})


@login_required
def question_delete(request, qid):
    question = get_object_or_404(Question, id=qid)
    question.delete()
    return redirect("blog:qna")





# Answer
@login_required
def answer_create(request, qid):
    '''
    답변등록
    1) question.answer_set.create()
    2) answer = Answer()
       answer.save()
    '''
    # 3번 방식 - form 이용
    question = get_object_or_404(Question,id=qid)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.question = question
            answer.author = request.user
            answer.save()
            return redirect("blog:question_detail", qid)
    else:
        form = AnswerForm()
    
    context = {"form":form, "question":question}

    return render(request, "blog/question_detail.html", context)

@login_required
def answer_modify(request,aid):
    """
    질문 수정 - form 사용
    """
    answer = get_object_or_404(Answer, id=aid ) # 수정할 대상 찾기
    if request.method == "POST":
        form = AnswerForm(request.POST, request.FILES, instance=answer) # instance= 찾은 대상 적어주기. 안쓰면 create 되어버림
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modified_at = timezone.now()
            answer.save()
            return redirect("blog:question_detail", answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    return render(request, "blog/answer_modify.html", {"form":form})

@login_required
def answer_delete(request, aid):
    answer = get_object_or_404(Answer, id=aid)
    answer.delete()
    return redirect("blog:question_detail" ,answer.question.id)







# Comment
@login_required
def comment_create_answer(request, aid):
    '''
    답변등록
    1) question.answer_set.create()
    2) answer = Answer()
       answer.save()
    '''
    # 3번 방식 - form 이용
    answer = get_object_or_404(Answer, id=aid)
    
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.answer = answer
            comment.save()
            return redirect("blog:question_detail", answer.question.id)
            # return redirect( "{}#comment_{}".format(
            #         resolve_url("blog:question_detail", answer.id),
            #         comment.id,
            #     ))
    else:
        form = CommentForm()
    
    context = {"form":form, "answer":answer}

    return render(request, "blog/question_detail.html", context)

@login_required
def comment_modify_answer(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modified_at = timezone.now()
            comment.save()
            return redirect("blog:question_detail", comment.answer.question.id)
            # return redirect(
            #     "{}#comment_{}".format(
            #         resolve_url("board:question_detail", comment.answer.question.id),
            #         comment.id,
            #     )
            # )
    else:
        form = CommentForm(instance=comment)
    return render(request, "blog/comment_form.html", {"form": form})

@login_required
def comment_delete_answer(request, cid):
    comment = get_object_or_404(Comment, id=cid)
    comment.delete()
    return redirect("blog:question_detail" ,comment.answer.question.id)

templates/blog/carousel.html
{% load static %}
{% comment %} <div><button class="customPrevBtn owlBtn">이전</button></div> {% endcomment %}
<div class="owl-carousel owl-theme owl-loaded ">
  
  <div class="owl-stage-outer">
    <div class="owl-stage" >
    <div class="owl-item">
      <a href="#" class=""><img class="rounded-5"src="{% static "img/carousel0.png" %}" ></a>
    </div>
    <div class="owl-item">
      <a href="#" class=""><img class="rounded-5"src="{% static "img/carousel1.png" %}" ></a>
    </div>
    <div class="owl-item">
   <a href="#" class=""><img class="rounded-5"src="{% static "img/carousel2.png" %}" ></a>
    </div>
   <div class="owl-item">
     <a href="#" class=""><img class="rounded-5"src="{% static "img/carousel3.png" %}" ></a>
   </div>
   <div class="owl-item">
     <a href="#" class=""><img class="rounded-5"src="{% static "img/carousel4.png" %}" ></a>
    </div>
  
  </div>
  
</div>


{% comment %} <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel" data-interval="1000">
  <!-- 하단의 indicators-->
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static "img/carousel0.jpeg" %}" class="d-block w-100 " alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "img/carousel1.jpg" %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "img/carousel2.png" %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div> {% endcomment %}





   

 

templates/blog/cart_page.html
{% extends "base.html" %}
{% load static %}
{% load filters %}
{% block style %}
  <link rel="stylesheet" href="{% static "css/cart.css" %}">
{% endblock style %}
{% block content %}

  <section class="cart">
    <div class="cart__information">
      <ul>

        <li>장바구니 상품은 최대 30일간 저장됩니다.</li>
        <li>가격, 옵션 등 정보가 변경된 경우 주문이 불가할 수 있습니다.</li>
        <li>오늘출발 상품은 판매자 설정 시점에 따라 오늘출발 여부가 변경될 수 있으니 주문 시 꼭 다시 확인해 주시기 바랍니다.</li>
      </ul>
    </div>
    <table class="cart__list">
      <form>
        <thead>
          <tr>
            <td><input type="checkbox"></td>
            <td colspan="2">상품정보</td>
            <td>수량</td>
            <td>상품금액</td>
            <td>배송비</td>
          </tr>
        </thead>
        <tbody>
          {% comment %} {{user.cart.cartitem_set.count}} {% endcomment %}
          {% for cart_item in user.cart.cartitem_set.all %}
            <tr class="cart__list__detail">
              <td><input type="checkbox"></td>
              <td><img class='cart' src="{{cart_item.item.image.url}}" alt="magic keyboard" style="width:250px; height:200px"></td>
              <td>

                <span class="cart__list__smartstore"></span>
                <p>{{cart_item.item.title}}</p>
                <sapn class="price">{{cart_item.item.price}}</sapn>
                <span style="text-decoration: line-through; color: lightgray;">{{cart_item.item.price}}</span>
              </td>
              <td class="cart__list__option">
                <p>{{cart_item.quantity}}개</p>
                <!-- Button trigger modal -->
                <button type="button" class="cart__list__optionbtn" data-bs-toggle="modal" data-bs-target="#exampleModal{{ cart_item.id }}">
                  주문조건 추가/변경
                </button>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal{{ cart_item.id }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered modal-lg">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">주문조건 추가/변경</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <div class="item d-flex justify-content-start mb-3 ms-3">
                          <div class=""><img class='cart' src="{{cart_item.item.image.url}}" alt="magic keyboard" style="width:100px; height:100px"></div>
                          <div class="ms-3">
                            <p>{{cart_item.item.title}}</p>
                            <sapn class="price">{{cart_item.item.price}}원</sapn>
                            <span style="text-decoration: line-through; color: lightgray;">{{cart_item.item.price}}</span> 
                          </div>
                        </div>
                        <hr style="width:90%; margin:0 auto; opacity: 10%;">
                        
                        <div class="container d-flex align-items-center mt-3">
                          <div><label for="readonlyInput" class="">배송방법</label></div>
                          <div class="ms-4 flex-grow-1"><input type="text" class="form-control pointer-events-none" id="readonlyInput" value="택배" readonly></div>
                        </div>
                        <div class="container d-flex align-items-center ">
                         <div><label for="readonlyInput" class="">배송비결제</label></div>
                         <div class="ms-2 flex-grow-1"><input type="text" class="form-control pointer-events-none" id="readonlyInput" value="2,500원 주문시 결제" readonly></div>
                        </div>
                        <span class="text-muted" style="margin-left:100px ;"> 제주 추가 3,000원, 그외 도서지역 추가 5,000원</span>

                        <hr style="width:90%; margin:0 auto; opacity: 10%;">

                        <div class="container d-flex align-items-center mt-3">
                          <div style="width:50px;"><label for="readonlyInput" class="">수량</label></div>
                          
                          <div class="input-group mb-3 ms-5 mt-3">
                            <button class="btn btn-outline-secondary" type="button">-</button>
                            <input id ="quantityInput" type="text" class="text-center" placeholder="" aria-label="Example text with two button addons" style="width: 60px;" value="{{cart_item.quantity}}">
                            <button class="btn btn-outline-secondary" type="button">+</button>
                          </div>
                        </div>
                     
                     
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                        <button type="button" class="btn btn-primary">확인</button>
                      </div>
                    </div>
                  </div>
                </div>


              </td>
              <td>
                <span class="price">{{ cart_item.item.price|multiply:cart_item.quantity }}원</span><br>
                <button class="cart__list__orderbtn">주문하기</button>
              </td>
              <td>무료</td>
            </tr>

          {% endfor %}
        </tbody>
        <tfoot>
          <tr>
            <td >
             
            </td>
            <td></td>
            <td colspan="3"> 선택상품금액 + 총 배송비 - 즉시할인예상금액 | 주문금액 147,000원</td>
            <td></td>
          </tr>

          
          <tr>
            <td colspan="3"><input type="checkbox">
              <button class="cart__list__optionbtn">선택상품 삭제</button>
              <button class="cart__list__optionbtn">선택상품 찜</button>
            </td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        </tfoot>
      </form>
    </table>
    <div class="cart__mainbtns">
      <button class="cart__bigorderbtn left">쇼핑 계속하기</button>
      <button class="cart__bigorderbtn right">주문하기</button>
    </div>
  </section>

{% endblock content %}
{% block script %}
<script src="js/cart_page.js"></script>
{% endblock script %}

templates/blog/question_list.html
{% extends "base.html" %}
{% comment %} {% load static board_filter %} {% endcomment %}
{% block content %}
  <div class="container my-3">
    <div class="d-flex justify-content-between">
      <h2>질문 게시판</h2>
      <a class="btn btn-light border" href="{% url "blog:faq" %}"> <i class="fa-regular fa-circle-question"></i> 자주 묻는 질문</a>
    </div>
    <div class="row my-3">
      <div class="input-group">
        <input type="text" name="keyword" id="" class="form-control">
        <button type="button" class="btn btn-outline-secondary" id="btn-search">찾기</button>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr class="thead-dark">
          <th>번호</th>

          <th style="width:50%">제목</th>
          <th>작성자</th>
          <th>작성일시</th>
        </tr>
      </thead>
      <tbody>
        <!-- 게시물 일련번호 = 전체게시물개수 - 시작 인덱스 - 현재인덱스(0~9) + 1 -->
        <!-- paginator.count : 전체 게시물 개수 -->
        <!-- start_index : 현재 페이지 시작 인덱스(1부터 시작) -->
        <!-- forloop.counter0 : for 루프 돌릴 때 인덱스는 0부터 시작 -->
        <!-- sub:커스텀 필터 호출, add:장고 필터 호출 -->
        {% for question in question_list %}
          <tr class="text-center">
            <td>{{question.id}}</td>
           
            <td>
              <a href="{% url "blog:question_detail" question.id %}" class="text-decoration-none text-reset">{{question.subject}}
                
            </td>
            <td>{{question.author.name}}</td>
            <td>{{question.created_at}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    {% comment %} <!-- 페이징 처리 paginator.page_range : 페이지 범위 -->
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if question_list.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{{question_list.previous_page_number}}" aria-label="Previous">
              previous
            </a>
          </li>
        {% endif %}
        {% for page in question_list.paginator.page_range %}
          {% if page >= question_list.number|add:-5 and page <= question_list.number|add:5%}
            <li class="page-item {% if page == question_list.number %}active{% endif %}">
              <a class="page-link" href="{{page}}">{{page}}</a>
            </li>
          {% endif %}
        {% endfor %}
        {% if question_list.has_next %}
          <li class="page-item">
            <a class="page-link" href="{{question_list.next_page_number}}" aria-label="Next">
              next
            </a>
          </li>
        {% endif %}
      </ul>
    </nav> {% endcomment %}

    <a href="{% url "blog:question_register" %}" class="btn btn-primary">질문 등록</a>
  </div>
{% endblock content %}
{% comment %} {% block script %}
  <script src="{% static "js/list.js" %}"></script>
{% endblock script %} {% endcomment %}