accounts/urls.py
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from . import views
# from .views import register

app_name = "accounts"

urlpatterns = [
    path(
        # http://127.0.0.1:8000/accounts/login/
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
        # http://127.0.0.1:8000/accounts/logout/
    # custom logout : post 형식만 가능..
    path("logout/", views.custom_logout, name="logout"),
        # http://127.0.0.1:8000/accounts/join/
    path("join/", views.register, name="join"),


     # My Page
    # http://127.0.0.1:8000/accounts/유저이름/mypage/
    # path("mypage/", views.mypage, name="mypage"),

    re_path(r"^(?P<nickname>[\w.@+-]+)/mypage/", views.mypage, name="mypage"), # re_path 하기
]

blog/urls.py
from django.urls import path, re_path
from . import views

app_name = 'blog'

urlpatterns = [
    # Item Zone
    # http://127.0.0.1:8000/blog/
    path('', views.index, name="index" ),
    # http://127.0.0.1:8000/blog/item/1
    path('item/<int:id>', views.item_detail, name="item_detail" ),
    # http://127.0.0.1:8000/blog/register/
    path('register/', views.item_register, name="item_register" ),
    # http://127.0.0.1:8000/blog/item/modify/1/
    path("item/modify/<int:pk>/", views.item_modify, name = "item_modify"),
    # http://127.0.0.1:8000/blog/item/delete/1/
    path("item/delete/<int:pk>/", views.item_delete, name = "item_delete"),







    # Question Zone
    # http://127.0.0.1:8000/blog/qna/
    path('qna/', views.qna, name="qna" ),
    # http://127.0.0.1:8000/blog/faq
    path('faq/', views.faq, name="faq" ),
    # http://127.0.0.1:8000/blog/qna/detail/1
    path('qna/detail/<int:qid>', views.question_detail, name="question_detail" ),
    # http://127.0.0.1:8000/blog/qna/register
    path('qna/register/', views.question_register, name="question_register" ),
    # http://127.0.0.1:8000/blog/qna/modify
    path('qna/modify/<int:qid>', views.question_modify, name="question_modify" ),
    # http://127.0.0.1:8000/blog/qna/delete
    path('qna/delete/<int:qid>', views.question_delete, name="question_delete" ),




    # Answer Zone
    # http://127.0.0.1:8000/blog/answer/create/1/
    path("answer/create/<int:qid>/", views.answer_create, name="answer_create"),
    # http://127.0.0.1:8000/blog/answer/delete/1/
    path("answer/delete/<int:aid>/", views.answer_delete, name="answer_delete"),
    # http://127.0.0.1:8000/blog/answer/modify/1/
    path("answer/modify/<int:aid>/", views.answer_modify, name="answer_modify"),



    # Comment Zone
    # http://127.0.0.1:8000/blog/comment/create/answer/aid/
    path("comment/create/answer/<int:aid>/", views.comment_create_answer, name="comment_create_answer"),
    # http://127.0.0.1:8000/blog/comment/modify/answer/aid/
    path("comment/modify/answer/<int:cid>/", views.comment_modify_answer, name="comment_modify_answer"),
    # http://127.0.0.1:8000/blog/comment/delete/answer/aid/
    path("comment/delete/answer/<int:cid>/", views.comment_delete_answer, name="comment_delete_answer"),





    # Cart Zone
    #  [\w.@+-]+ : \w == 0-9A-Za-z_ ,   . == 모든문자랑 매치 ,  @+- ,  + : 1~무한대
    #  ^ : 시작, $ : 종료
    # http://127.0.0.1:8000/blog/유저이름/cart/
    re_path(r"^(?P<nickname>[\w.@+-]+)/cart/", views.cart, name="cart"), # re_path 하기

    # http://127.0.0.1:8000/blog/cart/add/item_id
    path("cart/add/<int:item_id>/", views.add_to_cart, name="add_to_cart"),  # 장바구니에 추가 기능하기

    # http://127.0.0.1:8000/blog/cart/modify/item_id
    # path("cart/modify/<int:item_id>/", views.update_quantity, name="update_quantity"),  # 장바구니에 수량 변경

   




]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.index ),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base copy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Peach Market</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static "css/styles.css" %}" rel="stylesheet"/>
    <!-- owl carousel-->
    <link rel="stylesheet" href="{% static "css/owlcarousel/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "css/owlcarousel/owl.theme.default.min.css" %}">

    {% block style %}{% endblock style %}
  </head>

  <body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">
      <!-- Navigation-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky">
        <div class="container px-5">
          <a class="navbar-brand" href="{% url "blog:index" %}">Peach Market</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="index.html">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="about.html">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="contact.html">Contact</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="pricing.html">Pricing</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="faq.html">FAQ</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Blog</a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                  <li>
                    <a class="dropdown-item" href="blog-home.html">Blog Home</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="blog-post.html">Blog Post</a>
                  </li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Portfolio</a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                  <li>
                    <a class="dropdown-item" href="portfolio-overview.html">Portfolio Overview</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="portfolio-item.html">Portfolio Item</a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <!-- Header-->
      <header>
        {% block header %}{% endblock header %}
      </header>

      <!-- 본문 영역 -->
      <div class="container px-5 my-5">
        {% block content %}{% endblock content %}
      </div>

      <!-- Footer-->
      <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
          <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto">
              <div class="small m-0 text-white">Copyright &copy; Your Website 2023</div>
            </div>
            <div class="col-auto">
              <a class="link-light small" href="#!">Privacy</a>
              <span class="text-white mx-1">&middot;</span>
              <a class="link-light small" href="#!">Terms</a>
              <span class="text-white mx-1">&middot;</span>
              <a class="link-light small" href="#!">Contact</a>
            </div>
          </div>
        </div>
      </footer>
      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      <!-- Core theme JS-->
      <script src="{% static "js/scripts.js" %}"></script>
      <!-- owl carousel -->
      <script src="{% static "js/jquery.min.js" %}"></script>
      <script src="{% static "js/owl.carousel.min.js" %}"></script>
      {% block script %}{% endblock script %}
    </body>

  </html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Peach Market</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static "img/peach_icon.png" %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static "css/styles.css" %}" rel="stylesheet"/>

    <!-- Font Awesome -> 아이콘 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <!-- google font-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital@1&display=swap" rel="stylesheet">

    <!-- owl carousel -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
    <style>
      #mylogo {
        font-family: 'Lora', serif;
        font-size: 30px;
      }
    </style>
    {% block style %}{% endblock style %}
  </head>

  <body class="d-flex flex-column h-100">
    <main class="flex-shrink-0">

      <!-- Navigation-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container px-4 d-flex">
          {% comment %} <a class="navbar-brand" href="{% url "blog:index" %}" style="font-size:30px " id='mylogo'>Peach Market</a> {% endcomment %}
          <a class="navbar-brand"  href="{% url "blog:index" %}"  id='mylogo'>
            <img src="{% static "img/brand_logo.png" %}" alt="" width="70" height="70" >
            Peach Market
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>

          <!-- input group-->



                <div class="input-group input-group-sm p-2 w-100 " >
                  <form class="d-flex w-100">
                    <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-sm">    
                    <button type="submit" class="input-group-text" id="">
                      <i class="fa-solid fa-magnifying-glass"></i>
                    </button>
                  </form>
                </div>


  

     

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 ">

              {% if not user.is_authenticated %}
                <li class="nav-item p-0">
                  <a class="nav-link" href="{% url "accounts:login" %}">Login</a>
                </li>
                <li class="nav-item p-0">
                  <a class="nav-link" href="{% url "accounts:join" %}">SignUp</a>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url "blog:cart" user.nickname %}" style="font-size:21px;" >
                    <i class="fa-solid fa-cart-shopping"></i>
                  </a>
                </li>
                <li class="nav-item p-0">
                  <a class="nav-link" style="font-size:21px;" href="{% url "blog:item_register" %}"><i class="fa-solid fa-boxes-packing"></i></a>
                </li>
                
              
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="font-size:20px;">
                  <i class="fa-regular fa-user"></i> <span class="small">{{request.user.name}} 님</span></a>
                <ul class="dropdown-menu dropdown-menu-end" style="padding:0;" aria-labelledby="navbarDropdownBlog">
                  <li>
                    <a class="dropdown-item" href="{% url "accounts:mypage" user.nickname%}">
                      <i class="fa-regular fa-user"></i> MyPage</a> <!-- 비밀번호 변경 추가-->
                  </li>
             
                    <li class="nav-item">
                      <a class="dropdown-item" href="{% url "accounts:logout" %}">
                        <i class="fa-solid fa-arrow-right-from-bracket"></i> Logout</a>
                      </li>  
                      
                      {% endif %}
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <!-- Header-->
      {% block header %}{% endblock header %}

      <!-- 본문 영역 -->
      <div class="container px-5 my-5">
        {% block content %}{% endblock content %}
      </div>

      <!-- Footer-->
      <footer class="bg-dark py-4 mt-auto">
        <div class="container px-5">
          <div class="row align-items-center justify-content-between flex-column flex-sm-row">
            <div class="col-auto">
              <div class="small m-0 text-white">Copyright &copy; Your Website 2023</div>
            </div>
            <div class="col-auto">
              <a class="link-light small" href="#!">Privacy</a>
              <span class="text-white mx-1">&middot;</span>
              <a class="link-light small" href="#!">Terms</a>
              <span class="text-white mx-1">&middot;</span>
              <a class="link-light small" href="#!">Contact</a>
            </div>
          </div>
        </div>
      </footer>

      <!-- Bootstrap core JS-->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      <!-- Core theme JS-->
      <script src="{% static "js/scripts.js" %}"></script>

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <!-- Owl Carousel의 javascript CDN -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
      {% block script %}{% endblock script %}
    </body>

  </html>

templates/errors.html
{% if form.errors %}
  <div class="alert alert-danger">
    {% for field in form %}
      {% if field.errors %}
        <strong>{{field.label}}</strong>
        {{field.errors}}
      {% endif %}
    {% endfor %}
  </div>
{% endif %}